name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    uses: ./.github/workflows/_build.yml
    with:
      check-args: "--release"

  nix-build:
    uses: ./.github/workflows/_nix-build.yml
